#{{- $name := "disallow-capabilities" }}
#{{- if and (eq $name "disallow-capabilities") (eq .Values.podSecurityStandard.custom true) }}
  # Your Kyverno policy definition goes here
#{{- end }}
#
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-resources
spec:
  validationFailureAction: enforce
  rules:
    - name: validate-resource-limits
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Pods cannot request more than 4 GiB of memory or more than 4 CPU cores."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*Gi"
                    cpu: "?*"
                  requests:
                    memory: "?*Gi"
                    cpu: "?*"
        validate:
          message: "Resource limits exceeded: maximum memory is 4Gi and maximum CPU is 4."
          anyPattern:
            - spec:
                containers:
                  - resources:
                      limits:
                        memory: "!~^(5|[6-9]|[1-9][0-9]+)(Gi)$"
                        cpu: "!~^(5|[6-9]|[1-9][0-9]+)$"
            - spec:
                containers:
                  - resources:
                      requests:
                        memory: "!~^(5|[6-9]|[1-9][0-9]+)(Gi)$"
                        cpu: "!~^(5|[6-9]|[1-9][0-9]+)$"
