apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-resources
spec:
  validationFailureAction: enforce
  rules:
    - name: validate-resource-limits
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Pods cannot request more than 4096Mi of memory or more than 4000m of CPU."
        anyPattern:
          - spec:
              containers:
                - resources:
                    limits:
                      memory: "!~^(5[0-9]{2}[0-9]|[6-9][0-9]{2}|[1-9][0-9]{3,})(Mi)$"
                      cpu: "!~^(4001|[5-9][0-9]{2,}|[1-9][0-9]{3,})$"
          - spec:
              containers:
                - resources:
                    requests:
                      memory: "!~^(5[0-9]{2}[0-9]|[6-9][0-9]{2}|[1-9][0-9]{3,})(Mi)$"
                      cpu: "!~^(4001|[5-9][0-9]{2,}|[1-9][0-9]{3,})$"
