apiVersion: v2
name: kyverno
description: A Helm chart for Kyverno with custom subchart
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kyverno
    version: 2.7.1  # You can update this version as per your requirement
    repository: https://kyverno.github.io/kyverno/
    condition: kyverno.enabled  # Used to enable/disable Kyverno subchart
